"""Build and insert Section 11 (injection-induced fault reactivation) cells
into examples/embedded_crack_mohr_coulomb_ncp.ipynb.

Inserts six new cells before any trailing empty cells:
  C1 markdown : Section 11 header
  C2 code     : injection parameters (domain, fault, well, ramp)
  C3 code     : build CrackMeshBuilder + CGPoroelastostatics with point source
  C4 code     : build dynamic system + source-injected rhs wrapper
  C5 code     : projected-Radau time integration
  C6 code     : post-processing (slip(s,t), tip-position vs sqrt(t),
                pressure-field snapshots)

Re-runnable: detects existing inj_* cells by id and replaces them in place.
"""
from __future__ import annotations

import json
from pathlib import Path

NB_PATH = Path("/home/david/Documents/Solve_ivp_ns/examples/embedded_crack_mohr_coulomb_ncp.ipynb")

# --------------------------------------------------------------------- cells

CELL_HEADER_INJ = {
    "cell_type": "markdown",
    "id": "inj_header",
    "metadata": {},
    "source": [
        "## 11. Injection-induced fault reactivation\n",
        "\n",
        "Marginally stable fault driven into slip by an off-fault compact pressure\n",
        "source.  The fault sits inside the Mohr-Coulomb cone under the existing\n",
        "prestress (resolved shear $|\\tau| < \\mu\\sigma_N$).  A Wendland $C^{2}$\n",
        "injection source placed close to one tip raises the effective pore\n",
        "pressure on the fault, dropping $\\sigma_N - \\{\\!\\{p\\}\\!\\}$ until the\n",
        "Coulomb criterion is breached and the slip patch grows along the fault\n",
        "from the loaded tip outward (Garagash &amp; Germanovich 2012; Bhattacharya &amp;\n",
        "Viesca 2019, sealed-fault marginally-pressurised regime).\n",
        "\n",
        "Configuration:\n",
        "* domain $60 \\times 30$ m, fault length $L_f = 20$ m centred at\n",
        "  $(30,15)$, oriented at $\\theta_{\\rm Mohr}=35^{\\circ}$ — locked margin\n",
        "  $|\\tau|/\\mu\\sigma_N \\approx 0.85$, critical overpressure\n",
        "  $\\Delta p_c = \\sigma_N - |\\tau|/\\mu \\approx 5.5$ MPa;\n",
        "* sealed fault `T_Robin = 0` and `tangential_flow=False` — pressure\n",
        "  diffuses through the bulk, not across the fault;\n",
        "* compact Wendland source at $(20.1,11.7)$, $\\sim 3$ m perpendicular\n",
        "  off the lower-left tip, support radius $\\sim 1$ m so the source\n",
        "  footprint never crosses the fault;\n",
        "* rate-controlled injection $q(t) = q_{\\max} \\tanh(t/\\tau_{\\rm ramp})$\n",
        "  with $\\tau_{\\rm ramp}=5$ s — smooth start avoids exciting the wave\n",
        "  clock;\n",
        "* TMAX = 150 s — five times the prestress ramp window, gives the\n",
        "  pressure pulse room to traverse the fault and the slip patch room\n",
        "  to grow.\n",
        "\n",
        "All other settings (`ALPHA_BIOT`, wave-clock override, Lysmer absorbing\n",
        "boundary, Mohr-Coulomb constant friction, projected Radau IIA $s=2$)\n",
        "are inherited from the configuration cells above.\n"
    ],
}

CELL_PARAMS_INJ = {
    "cell_type": "code",
    "id": "inj_params",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# --- Domain and fault geometry (PHYSICAL units, m) -----------------------\n",
        "XMIN_INJ, XMAX_INJ = 0.0, 60.0\n",
        "YMIN_INJ, YMAX_INJ = 0.0, 30.0\n",
        "N_ELEM_INJ        = 80\n",
        "\n",
        "CRACK_LENGTH_INJ  = 20.0\n",
        "CRACK_X0_INJ      = 0.5 * (XMIN_INJ + XMAX_INJ)\n",
        "CRACK_Y0_INJ      = 0.5 * (YMIN_INJ + YMAX_INJ)\n",
        "\n",
        "# Marginally stable orientation: theta_Mohr = 35 deg => CRACK_THETA = 55 deg\n",
        "THETA_MARGINAL    = np.radians(35.0)\n",
        "CRACK_THETA_INJ   = np.pi / 2 - THETA_MARGINAL\n",
        "\n",
        "sigma_N_inj_phys, tau_inj_phys = mohr_tractions(THETA_MARGINAL)\n",
        "delta_p_crit_phys = sigma_N_inj_phys - abs(tau_inj_phys) / MU\n",
        "_locked_ratio = abs(tau_inj_phys) / (MU * sigma_N_inj_phys)\n",
        "print(f\"theta_Mohr = {np.degrees(THETA_MARGINAL):.1f} deg, \"\n",
        "      f\"crack_theta = {np.degrees(CRACK_THETA_INJ):.1f} deg\")\n",
        "print(f\"sigma_N = {sigma_N_inj_phys:.2f} MPa, tau = {tau_inj_phys:.2f} MPa, \"\n",
        "      f\"|tau|/(mu sigma_N) = {_locked_ratio:.3f}  (locked)\")\n",
        "print(f\"critical overpressure Delta p_c = {delta_p_crit_phys:.3f} MPa\")\n",
        "\n",
        "# --- Fault tip locations (used to place the well) ------------------------\n",
        "_t_inj = np.array([np.sin(CRACK_THETA_INJ), np.cos(CRACK_THETA_INJ)])\n",
        "_n_inj = np.array([-np.cos(CRACK_THETA_INJ), np.sin(CRACK_THETA_INJ)])\n",
        "TIP_LO_INJ = np.array([CRACK_X0_INJ, CRACK_Y0_INJ]) - 0.5 * CRACK_LENGTH_INJ * _t_inj\n",
        "TIP_HI_INJ = np.array([CRACK_X0_INJ, CRACK_Y0_INJ]) + 0.5 * CRACK_LENGTH_INJ * _t_inj\n",
        "\n",
        "# Well: 3 m perpendicular off the lower-left tip\n",
        "WELL_OFFSET_PHYS  = 3.0\n",
        "WELL_LOC_PHYS     = TIP_LO_INJ + WELL_OFFSET_PHYS * _n_inj\n",
        "POINT_SOURCE_LOC_INJ = np.array([WELL_LOC_PHYS])  # (1,2) physical metres\n",
        "\n",
        "# Compact source: physical radius ~ 1 m  (R = 2 sigma = 2 * sources_RMS_width * char_length)\n",
        "_char_len_inj = max(XMAX_INJ - XMIN_INJ, YMAX_INJ - YMIN_INJ) / SCALE_L\n",
        "SOURCE_R_PHYS         = 1.0\n",
        "SOURCES_RMS_WIDTH_INJ = SOURCE_R_PHYS / (2.0 * _char_len_inj)\n",
        "\n",
        "# --- Injection schedule --------------------------------------------------\n",
        "# Rate-controlled tanh ramp.  Q_INJ_PEAK is in dimensional units of an\n",
        "# integrated 2D source (volumetric flux, m^2/s); tune to drive {{p}} on\n",
        "# the fault past Delta_p_c.  Library normalises Bp so int(Bp_j) = 1.\n",
        "Q_INJ_PEAK    = 1.0\n",
        "TAU_RAMP_INJ  = 5.0       # s\n",
        "\n",
        "TMAX_PHYS_INJ = 150.0     # s, ~5x the prestress ramp window\n",
        "TMAX_INJ      = TMAX_PHYS_INJ / T_scale\n",
        "H0_INJ        = H_FIXED\n",
        "ADAPTIVE_H_MAX_INJ = TMAX_INJ / 10.0\n",
        "\n",
        "def q_inj_phys(t_dim):\n",
        "    \"\"\"Physical injection rate [m^2/s] vs dimensionless time.\"\"\"\n",
        "    t_phys = float(t_dim) * T_scale\n",
        "    return Q_INJ_PEAK * np.tanh(t_phys / TAU_RAMP_INJ) * np.ones(1)\n",
        "\n",
        "print(f\"domain: [{XMIN_INJ},{XMAX_INJ}] x [{YMIN_INJ},{YMAX_INJ}] m, \"\n",
        "      f\"N_ELEM = {N_ELEM_INJ}\")\n",
        "print(f\"fault: centre=({CRACK_X0_INJ},{CRACK_Y0_INJ}) m, length={CRACK_LENGTH_INJ} m\")\n",
        "print(f\"  tip_lo  = ({TIP_LO_INJ[0]:.2f},{TIP_LO_INJ[1]:.2f}) m\")\n",
        "print(f\"  tip_hi  = ({TIP_HI_INJ[0]:.2f},{TIP_HI_INJ[1]:.2f}) m\")\n",
        "print(f\"well loc = ({WELL_LOC_PHYS[0]:.2f},{WELL_LOC_PHYS[1]:.2f}) m, \"\n",
        "      f\"R_source = {SOURCE_R_PHYS:.2f} m  (sources_RMS_width = {SOURCES_RMS_WIDTH_INJ:.4f})\")\n",
        "print(f\"injection: q_max = {Q_INJ_PEAK} m^2/s, tau_ramp = {TAU_RAMP_INJ} s\")\n",
        "print(f\"time horizon: TMAX_PHYS = {TMAX_PHYS_INJ} s  (dimensionless TMAX = {TMAX_INJ:.3g})\")\n"
    ],
}

CELL_BUILD_INJ = {
    "cell_type": "code",
    "id": "inj_build",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "builder_inj = CrackMeshBuilder(\n",
        "    XMIN_INJ, XMAX_INJ, YMIN_INJ, YMAX_INJ, N_ELEM_INJ,\n",
        "    crack_theta=CRACK_THETA_INJ,\n",
        "    crack_x0=CRACK_X0_INJ, crack_y0=CRACK_Y0_INJ,\n",
        "    crack_length=CRACK_LENGTH_INJ,\n",
        "    element_type='tri', conforming=CONFORMING_CRACK_MESH,\n",
        "    verbose=True,\n",
        ")\n",
        "mesh_inj, el_p_inj, el_u_inj, crack_inj, h_mesh_inj = builder_inj.build()\n",
        "\n",
        "bc_inj = make_bc()\n",
        "\n",
        "poro_inj = CGPoroelastostatics(\n",
        "    mesh=mesh_inj,\n",
        "    element_p=el_p_inj,\n",
        "    element_u=el_u_inj,\n",
        "    params=PARAMS, material=MATERIAL,\n",
        "    crack=crack_inj,\n",
        "    model_params=CRACK_MODEL_PARAMS,\n",
        "    intorder=6,\n",
        "    scales=(SCALE_L, SCALE_EPS),\n",
        "    bc=bc_inj,\n",
        "    P_scale=None,\n",
        "    verbose=True,\n",
        "    free_memory=False,\n",
        "    enforcement_type='nodal',\n",
        "    apply_transform=True,\n",
        "    include_taylor=INCLUDE_TAYLOR,\n",
        "    include_taylor_test=INCLUDE_TAYLOR_TEST,\n",
        "    include_hessian=INCLUDE_HESSIAN,\n",
        "    include_sbm=INCLUDE_SBM,\n",
        "    taylor_method='nodal',\n",
        "    lumped_coupling='consistent',\n",
        "    crack_law='nonsmooth',\n",
        "    rotate_crack_to_nt=True,\n",
        "    bulk_viscosity={'mu_v': BULK_MU_V, 'lam_v': BULK_LAM_V},\n",
        "    point_source_location=POINT_SOURCE_LOC_INJ,\n",
        "    sources_RMS_width=SOURCES_RMS_WIDTH_INJ,\n",
        "    source_type='wendland',\n",
        ")\n",
        "\n",
        "poro_inj.strip_multiplier_dynamics()\n",
        "projection_inj, meta_inj = poro_inj.build_projection()\n",
        "dyn_inj = poro_inj.build_first_order_dynamic_system(meta_inj)\n",
        "\n",
        "A_dyn_inj          = dyn_inj['A']\n",
        "rhs_dyn_inj        = dyn_inj['rhs']\n",
        "rhs_jac_dyn_inj    = dyn_inj['rhs_jac']\n",
        "velocity_slice_inj = dyn_inj['velocity_slice']\n",
        "n_base_inj         = dyn_inj['n_base']\n",
        "comp_slices_inj    = dyn_inj['component_slices']\n",
        "\n",
        "Np_inj = poro_inj.basis_p.N\n",
        "Nu_inj = poro_inj.basis_u.N\n",
        "\n",
        "_, _, _, _, _, Q_scale_inj, _ = poro_inj.get_scales()\n",
        "Bp_inj = poro_inj.Bp.tocsr()\n",
        "assert Bp_inj.shape == (Np_inj, 1), f\"unexpected Bp shape {Bp_inj.shape}\"\n",
        "\n",
        "print(f\"injection mesh: {mesh_inj.nelements} elements, {mesh_inj.p.shape[1]} vertices, \"\n",
        "      f\"h ~ {h_mesh_inj:.3f}\")\n",
        "print(f\"n_base = {n_base_inj}, |x| = {A_dyn_inj.shape[0]}, Np = {Np_inj}, Nu = {Nu_inj}\")\n",
        "print(f\"Q_scale = {Q_scale_inj:.3e} (dimensional rate / Q_scale -> dimensionless source coeff)\")\n"
    ],
}

CELL_AUG_INJ = {
    "cell_type": "code",
    "id": "inj_aug",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "info_inj = poro_inj._transform_info\n",
        "n_c_inj  = int(poro_inj.n_lambda_q)\n",
        "\n",
        "lam_s_sl_inj = meta_inj['lam_s_sl']\n",
        "\n",
        "off_jmpu_inj  = info_inj['off_jmpu']\n",
        "n_iu_inj      = info_inj['n_intf_u']\n",
        "off_jmpls_inj = info_inj['off_jmpls']\n",
        "n_lsig_inj    = info_inj['n_lam_sig']\n",
        "\n",
        "jmpu_n_idx_inj = np.arange(off_jmpu_inj, off_jmpu_inj + n_c_inj)\n",
        "jmpu_t_idx_inj = np.arange(off_jmpu_inj + n_c_inj, off_jmpu_inj + n_iu_inj)\n",
        "jmpu_all_inj   = np.concatenate([jmpu_n_idx_inj, jmpu_t_idx_inj])\n",
        "jmpls_cols_inj = np.arange(off_jmpls_inj, off_jmpls_inj + n_lsig_inj)\n",
        "\n",
        "T_u_inj = dyn_inj['T_u']\n",
        "u_idx_inj = dyn_inj['u_state_indices']\n",
        "jmpu_local_inj = np.searchsorted(u_idx_inj, jmpu_all_inj)\n",
        "assert np.all(u_idx_inj[jmpu_local_inj] == jmpu_all_inj)\n",
        "D_inj = T_u_inj[jmpu_local_inj, :].tocsr()\n",
        "\n",
        "R_v_inj = dyn_inj.get('R_v')\n",
        "A_csr_inj = poro_inj.A.tocsr()\n",
        "B_u_inj = (A_csr_inj[Np_inj:Np_inj + Nu_inj, :][:, jmpls_cols_inj]).tocsr()\n",
        "if R_v_inj is not None:\n",
        "    B_u_inj = (R_v_inj @ B_u_inj).tocsr()\n",
        "\n",
        "dirichlet_local_inj = np.array(\n",
        "    [d - Np_inj for d in np.asarray(getattr(poro_inj, '_dirichlet_dof_set', []), dtype=int)\n",
        "     if Np_inj <= d < Np_inj + Nu_inj],\n",
        "    dtype=int,\n",
        ")\n",
        "if dirichlet_local_inj.size:\n",
        "    B_u_inj = B_u_inj.tolil()\n",
        "    B_u_inj[dirichlet_local_inj, :] = 0.0\n",
        "    B_u_inj = B_u_inj.tocsr()\n",
        "\n",
        "perm_inj = [idx for k in range(n_c_inj) for idx in (k, n_c_inj + k)]\n",
        "B_u_perm_inj = B_u_inj[:, perm_inj].tocsr()\n",
        "reaction_rows_inj = np.array([row for k in range(n_c_inj) for row in (k, n_c_inj + k)], dtype=int)\n",
        "\n",
        "contacts_inj = [\n",
        "    {'vel_normal_idx': k, 'vel_tangential_idx': [n_c_inj + k], 'mu': MU, 'e': 0.0}\n",
        "    for k in range(n_c_inj)\n",
        "]\n",
        "\n",
        "n_phys_inj = A_dyn_inj.shape[0]\n",
        "n_extract_inj = 2 * n_c_inj\n",
        "gap_extract_dyn_inj = sp.csr_matrix(\n",
        "    (np.ones(n_extract_inj), (np.arange(n_extract_inj), jmpu_all_inj)),\n",
        "    shape=(n_extract_inj, n_phys_inj),\n",
        ")\n",
        "vel_extract_dyn_inj = sp.hstack(\n",
        "    [sp.csr_matrix((n_extract_inj, n_base_inj)), D_inj], format='csr',\n",
        ")\n",
        "B_c_dyn_inj = sp.vstack(\n",
        "    [sp.csr_matrix((n_base_inj, B_u_perm_inj.shape[1])), B_u_perm_inj], format='csr',\n",
        ")\n",
        "B_n_dyn_inj = B_c_dyn_inj[:, 0::2]\n",
        "B_t_dyn_inj = B_c_dyn_inj[:, 1::2]\n",
        "\n",
        "off_avgp_inj = info_inj['off_avgp']\n",
        "n_intf_p_inj = info_inj['n_intf_p']\n",
        "assert n_intf_p_inj == n_c_inj, \"one pore-pressure trace value per contact node\"\n",
        "p_gamma_extract_dyn_inj = sp.csr_matrix(\n",
        "    (np.ones(n_c_inj), (np.arange(n_c_inj), off_avgp_inj + np.arange(n_c_inj))),\n",
        "    shape=(n_c_inj, n_phys_inj),\n",
        ")\n",
        "pressure_normal_correction_inj = -ALPHA_BIOT * (B_n_dyn_inj @ p_gamma_extract_dyn_inj)\n",
        "pressure_normal_correction_inj.eliminate_zeros()\n",
        "\n",
        "# Defensive helpers (no-op if already defined by an earlier section)\n",
        "if '_contact_offset_vector' not in globals():\n",
        "    def _contact_offset_vector(s0, w0):\n",
        "        s0 = np.asarray(s0, dtype=float).ravel()\n",
        "        w0 = np.asarray(w0, dtype=float).ravel()\n",
        "        out = np.zeros(2 * s0.size)\n",
        "        out[0::2] = s0\n",
        "        out[1::2] = w0\n",
        "        return out\n",
        "if '_constraint_residual_inf' not in globals():\n",
        "    def _constraint_residual_inf(model, y_phys):\n",
        "        proj = getattr(model, 'algebraic_projection', None)\n",
        "        slices = getattr(model, 'constraint_q_slices', None)\n",
        "        if proj is None or not slices:\n",
        "            return 0.0\n",
        "        residual = proj.constraint_residual(np.asarray(y_phys, dtype=float))\n",
        "        return float(max(np.linalg.norm(residual[sl], ord=np.inf) for sl in slices))\n",
        "if '_contact_history' not in globals():\n",
        "    def _contact_history(y_hist, n_phys, n_contact, s0, w0):\n",
        "        y_hist = np.asarray(y_hist, dtype=float)\n",
        "        r_pert = y_hist[:, n_phys:n_phys + 2 * n_contact]\n",
        "        r_total = r_pert + _contact_offset_vector(s0, w0)[None, :]\n",
        "        return r_pert, r_total, r_total[:, 0::2], r_total[:, 1::2]\n",
        "\n",
        "if USE_LYSMER:\n",
        "    _C_lysmer_inj = lysmer_descriptor_block(\n",
        "        poro_inj, n_phys_inj, n_base_inj, a_p=LYSMER_AP, a_s=LYSMER_AS,\n",
        "    )\n",
        "else:\n",
        "    _C_lysmer_inj = None\n",
        "\n",
        "if USE_WINKLER:\n",
        "    _K_winkler_inj = winkler_descriptor_block(\n",
        "        poro_inj, n_phys_inj, n_base_inj,\n",
        "        u_state_indices=dyn_inj['u_state_indices'],\n",
        "        b_p=WINKLER_BP, b_s=WINKLER_BS,\n",
        "    )\n",
        "else:\n",
        "    _K_winkler_inj = None\n",
        "\n",
        "# Source contribution lives entirely in the pressure-balance rows of dyn rhs.\n",
        "# row_p indices in dyn state are the first Np entries (z-block).\n",
        "_src_row = np.arange(Np_inj)\n",
        "\n",
        "def _injection_source_vec(t):\n",
        "    \"\"\"Bp @ (q_total(t) / Q_scale) embedded into the dynamic state.\"\"\"\n",
        "    src = (Bp_inj @ q_inj_phys(t)) / Q_scale_inj\n",
        "    out = np.zeros(n_phys_inj + (A_dyn_inj.shape[0] - n_phys_inj), dtype=float)\n",
        "    # Dyn state layout: [z (n_base = Np + Nu + n_lam), v (Nu)]\n",
        "    # Pressure rows are the first Np entries of z (and of n_phys = n_base + Nu? no, n_phys = A_dyn.shape[0]).\n",
        "    out[_src_row] = src.ravel()\n",
        "    return out\n",
        "\n",
        "def rhs_dyn_inj_eff(t, y, *extra):\n",
        "    out = rhs_dyn_inj(t, y, *extra) + pressure_normal_correction_inj @ y\n",
        "    if _C_lysmer_inj is not None:\n",
        "        out = out - _C_lysmer_inj @ y\n",
        "    if _K_winkler_inj is not None:\n",
        "        out = out - _K_winkler_inj @ y\n",
        "    out = out + _injection_source_vec(t)\n",
        "    return out\n",
        "\n",
        "def rhs_jac_dyn_inj_eff(t, y, *extra):\n",
        "    J = rhs_jac_dyn_inj(t, y, *extra) + pressure_normal_correction_inj\n",
        "    if _C_lysmer_inj is not None:\n",
        "        J = J - _C_lysmer_inj\n",
        "    if _K_winkler_inj is not None:\n",
        "        J = J - _K_winkler_inj\n",
        "    return J\n",
        "\n",
        "# Prestress contact offsets at the marginal orientation\n",
        "_sN_phys_inj, _tau_phys_inj = prestress_offsets(sigma_N_inj_phys, tau_inj_phys)\n",
        "_s0_val_inj = np.full(n_c_inj, 2.0 * _sN_phys_inj / Sigma_scale)\n",
        "_w0_val_inj = np.full(n_c_inj, 2.0 * _tau_phys_inj / Sigma_scale)\n",
        "\n",
        "def get_s0_inj(y):\n",
        "    return _s0_val_inj\n",
        "\n",
        "def get_w0_inj(y, k):\n",
        "    return np.array([_w0_val_inj[int(k)]])\n",
        "\n",
        "flux_constraint_inj = meta_inj['constraints'][0]\n",
        "n_lam_s_dim_inj = int(lam_s_sl_inj.stop - lam_s_sl_inj.start)\n",
        "zero_lam_s_inj = {\n",
        "    'g': lambda zf, *_a, _n=n_lam_s_dim_inj: np.zeros(_n),\n",
        "    'dg_dy': lambda zf, *_a, _n=n_lam_s_dim_inj: np.zeros((_n, _n)),\n",
        "    'y_slice': lam_s_sl_inj,\n",
        "    'q_slice': lam_s_sl_inj,\n",
        "}\n",
        "\n",
        "cs_inj = build_projected_radau_contact(\n",
        "    A_dyn_inj,\n",
        "    rhs_dyn_inj_eff,\n",
        "    np.zeros(A_dyn_inj.shape[0]),\n",
        "    contacts=contacts_inj,\n",
        "    C_extract=gap_extract_dyn_inj,\n",
        "    D_extract=vel_extract_dyn_inj,\n",
        "    B=B_c_dyn_inj,\n",
        "    constraints=[flux_constraint_inj, zero_lam_s_inj],\n",
        "    component_slices=comp_slices_inj,\n",
        "    rhs_jac=rhs_jac_dyn_inj_eff,\n",
        "    get_s0=get_s0_inj,\n",
        "    get_w0=get_w0_inj,\n",
        "    normal_r='auto',\n",
        "    friction_r='auto',\n",
        "    endpoint_inactive_handling='natural_map',\n",
        "    contact_law=CONTACT_LAW,\n",
        "    reported_reaction_units='force',\n",
        "    auto_rho_strategy='delassus',\n",
        ")\n",
        "print(f\"injection contact system: A={cs_inj.A.shape}, |y0|={cs_inj.y0.size}\")\n"
    ],
}

CELL_SOLVE_INJ = {
    "cell_type": "code",
    "id": "inj_solve",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "n_aug_inj  = cs_inj.y0.size\n",
        "n_phys_aug = A_dyn_inj.shape[0]\n",
        "\n",
        "nl_atol_inj = np.full(n_aug_inj, 1e-8)\n",
        "nl_rtol_inj = np.full(n_aug_inj, 1e-6)\n",
        "nl_atol_inj[n_phys_aug:] = 1e-12\n",
        "nl_rtol_inj[n_phys_aug:] = 0.0\n",
        "\n",
        "solver_opts_inj = dict(cs_inj.solver_opts)\n",
        "solver_opts_inj.update(\n",
        "    tol=1e-8,\n",
        "    max_iter=50,\n",
        "    rhs_jac=cs_inj.rhs_jac,\n",
        "    linear_solver='petsc',\n",
        "    petsc_options={\n",
        "        'ksp_type': 'preonly',\n",
        "        'pc_type': 'lu',\n",
        "        'pc_factor_mat_solver_type': 'mumps',\n",
        "    },\n",
        "    petsc_reuse_steps=50,\n",
        ")\n",
        "\n",
        "integrator_opts_inj = dict(cs_inj.integrator_opts)\n",
        "integrator_opts_inj.update({'stages': 2, 'use_coupled_newton': True})\n",
        "\n",
        "y0_inj = (lambda _y: (_y.__setitem__(slice(-2 * n_c_inj, None),\n",
        "    coulomb_cone_warm_start(_s0_val_inj, _w0_val_inj, MU)) or _y))(cs_inj.y0.copy())\n",
        "\n",
        "print(f\"Solving injection-driven reactivation: \"\n",
        "      f\"projected Radau IIA s=2 (PETSc/MUMPS), \"\n",
        "      f\"h0={H0_INJ}, tmax={TMAX_INJ:.3g}, rtol={ADAPTIVE_RTOL}, atol={ADAPTIVE_ATOL}\")\n",
        "\n",
        "(\n",
        "    t_inj, y_inj, h_inj, fk_inj, info_inj_run, attempts_inj\n",
        ") = solve_nivp.solve_ivp_ns(\n",
        "    fun=cs_inj.rhs,\n",
        "    t_span=(0.0, float(TMAX_INJ)),\n",
        "    y0=y0_inj,\n",
        "    method='radau_iia',\n",
        "    integrator_opts=integrator_opts_inj,\n",
        "    projection=cs_inj.projection,\n",
        "    solver='semismooth_newton',\n",
        "    projection_opts={'component_slices': cs_inj.component_slices},\n",
        "    solver_opts=solver_opts_inj,\n",
        "    adaptive=True,\n",
        "    h0=H0_INJ,\n",
        "    rtol=ADAPTIVE_RTOL,\n",
        "    atol=ADAPTIVE_ATOL,\n",
        "    skip_error_indices=[0, len(cs_inj.component_slices) - 1],\n",
        "    active_set_filter=False,\n",
        "    return_attempts=True,\n",
        "    adaptive_opts=dict(\n",
        "        h0=H0_INJ, h_min=ADAPTIVE_H_MIN, h_max=ADAPTIVE_H_MAX_INJ,\n",
        "        h_up=2.0, h_down=0.5, method_order=1,\n",
        "    ),\n",
        "    nl_atol=nl_atol_inj,\n",
        "    nl_rtol=nl_rtol_inj,\n",
        "    component_slices=cs_inj.component_slices,\n",
        "    verbose=True,\n",
        "    A=cs_inj.A,\n",
        "    dae_var_weight='auto',\n",
        ")\n",
        "\n",
        "y_inj = np.asarray(y_inj, dtype=float)\n",
        "t_inj = np.asarray(t_inj, dtype=float)\n",
        "h_arr_inj = np.asarray(h_inj, dtype=float)\n",
        "acc_inj = np.asarray(attempts_inj, dtype=bool) if attempts_inj is not None else None\n",
        "n_acc_inj = int(acc_inj.sum()) if acc_inj is not None else len(t_inj) - 1\n",
        "n_rej_inj = int((~acc_inj).sum()) if acc_inj is not None else 0\n",
        "print(f\"Done: {len(t_inj)} states, t_final = {t_inj[-1]:.4e} \"\n",
        "      f\"(physical {t_inj[-1]*T_scale:.2f} s); \"\n",
        "      f\"steps accepted={n_acc_inj}, rejected={n_rej_inj}; \"\n",
        "      f\"h range=[{h_arr_inj.min():.2e}, {h_arr_inj.max():.2e}], \"\n",
        "      f\"median h={np.median(h_arr_inj):.2e}\")\n",
        "\n",
        "# Slip and contact reactions over the trajectory\n",
        "inj_gap  = np.asarray(y_inj[:, jmpu_n_idx_inj], dtype=float)\n",
        "inj_slip = np.asarray(y_inj[:, jmpu_t_idx_inj], dtype=float)\n",
        "r_pert_inj_full, r_total_inj_full, r_n_inj_full_nd, r_t_inj_full_nd = _contact_history(\n",
        "    y_inj, n_phys_inj, n_c_inj, _s0_val_inj, _w0_val_inj,\n",
        ")\n",
        "r_n_inj_full = r_n_inj_full_nd * Sigma_scale\n",
        "r_t_inj_full = r_t_inj_full_nd * Sigma_scale\n",
        "inj_cone_margin = MU * r_n_inj_full - np.abs(r_t_inj_full)\n",
        "print(f\"max |slip| (dimensionless) = {np.max(np.abs(inj_slip)):.3e}, \"\n",
        "      f\"min cone margin (post-IC) = {inj_cone_margin[1:].min():.3e} MPa\")\n"
    ],
}

CELL_POST_INJ = {
    "cell_type": "code",
    "id": "inj_post",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# Sort interface DOFs by arclength along the fault tangent.  Use mesh.p\n",
        "# / mesh.t for bulk-field plots (NOT basis_p.global_coordinates(), which\n",
        "# returns quadrature-point coords with shape (dim, n_elem, n_qp)).\n",
        "_lam_coords_inj = poro_inj._nodal_interface_info['lambda_coords']\n",
        "_lam_xy_inj = np.asarray(_lam_coords_inj, dtype=float).reshape(n_c_inj, -1)[:, :2]\n",
        "_lam_centred_inj = _lam_xy_inj - _lam_xy_inj.mean(axis=0)\n",
        "_U_lam_inj, _, _ = np.linalg.svd(_lam_centred_inj.T, full_matrices=False)\n",
        "_tan_inj = _U_lam_inj[:, 0]\n",
        "if np.dot(_tan_inj, _t_inj) < 0:\n",
        "    _tan_inj = -_tan_inj\n",
        "xi_phys_inj = (_lam_centred_inj @ _tan_inj) * SCALE_L\n",
        "_sort_inj = np.argsort(xi_phys_inj)\n",
        "xi_inj_sorted = xi_phys_inj[_sort_inj]\n",
        "\n",
        "slip_phys_inj  = inj_slip[:, _sort_inj] * DISP_UNIT_TO_PHYS\n",
        "r_n_inj_sorted = r_n_inj_full[:, _sort_inj]\n",
        "r_t_inj_sorted = r_t_inj_full[:, _sort_inj]\n",
        "cone_inj_sorted = inj_cone_margin[:, _sort_inj]\n",
        "t_phys_inj = t_inj * T_scale\n",
        "\n",
        "# Slip-active mask (above threshold)\n",
        "_slip_thr = 1e-6 * max(1.0, np.max(np.abs(slip_phys_inj)))\n",
        "slip_active_inj = np.abs(slip_phys_inj) > _slip_thr\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(13, 9), constrained_layout=True)\n",
        "\n",
        "# (a) slip(s, t) waterfall\n",
        "ax = axes[0, 0]\n",
        "im = ax.pcolormesh(\n",
        "    xi_inj_sorted, t_phys_inj, slip_phys_inj,\n",
        "    shading='auto', cmap='RdBu_r',\n",
        "    vmin=-np.max(np.abs(slip_phys_inj)) - 1e-30,\n",
        "    vmax= np.max(np.abs(slip_phys_inj)) + 1e-30,\n",
        ")\n",
        "ax.set_xlabel('arclength along fault [m]')\n",
        "ax.set_ylabel('t [s]')\n",
        "ax.set_title('slip $[\\\\!\\\\![u_t]\\\\!\\\\!]$ along fault vs time [m]')\n",
        "fig.colorbar(im, ax=ax)\n",
        "\n",
        "# (b) slip-tip position vs sqrt(t)\n",
        "ax = axes[0, 1]\n",
        "tip_pos_inj = np.full(t_phys_inj.size, np.nan)\n",
        "for k, mask in enumerate(slip_active_inj):\n",
        "    if mask.any():\n",
        "        tip_pos_inj[k] = xi_inj_sorted[np.where(mask)[0].max()]\n",
        "_valid = np.isfinite(tip_pos_inj)\n",
        "if _valid.any():\n",
        "    ax.plot(np.sqrt(t_phys_inj[_valid]), tip_pos_inj[_valid], 'k.-', ms=3)\n",
        "    ax.set_xlabel(r'$\\sqrt{t}\\;[\\sqrt{\\mathrm{s}}]$')\n",
        "    ax.set_ylabel('rightmost slipping arclength [m]')\n",
        "    ax.set_title('slip-front position vs $\\\\sqrt{t}$')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "else:\n",
        "    ax.text(0.5, 0.5, 'no slip yet', ha='center', va='center', transform=ax.transAxes)\n",
        "    ax.set_title('slip-front position vs $\\\\sqrt{t}$')\n",
        "\n",
        "# (c) cone margin (min over fault) vs time -- shows reactivation onset\n",
        "ax = axes[1, 0]\n",
        "ax.plot(t_phys_inj, np.min(cone_inj_sorted, axis=1), 'r-', lw=1.2, label='min over fault')\n",
        "ax.plot(t_phys_inj, np.median(cone_inj_sorted, axis=1), 'b--', lw=1.0, label='median')\n",
        "ax.axhline(0.0, color='k', lw=0.6)\n",
        "ax.set_xlabel('t [s]')\n",
        "ax.set_ylabel(r'cone margin $\\mu R_n - |R_t|$ [MPa]')\n",
        "ax.set_title('cone margin vs time (negative = sliding)')\n",
        "ax.legend(loc='best', fontsize=9)\n",
        "ax.grid(True, alpha=0.3)\n",
        "\n",
        "# (d) interface pressure {{p}} along fault vs time -- the actual\n",
        "# loading on the Mohr-Coulomb cone (sigma_N - {{p}}).  The 2D bulk\n",
        "# pressure field is shown by the time-resolved dashboard cell below;\n",
        "# {{p}} on the fault is what drives slip and is NOT in the dashboard.\n",
        "ax = axes[1, 1]\n",
        "P_scale_inj = poro_inj.get_scales()[2]\n",
        "_avg_p_cols = off_avgp_inj + np.arange(n_c_inj)\n",
        "avg_p_inj = y_inj[:, _avg_p_cols] * P_scale_inj   # (n_t, n_c) in MPa\n",
        "avg_p_inj_sorted = avg_p_inj[:, _sort_inj]\n",
        "_pmax = max(np.max(np.abs(avg_p_inj_sorted)), 1e-30)\n",
        "im_p = ax.pcolormesh(\n",
        "    xi_inj_sorted, t_phys_inj, avg_p_inj_sorted,\n",
        "    shading='auto', cmap='RdBu_r', vmin=-_pmax, vmax=_pmax,\n",
        ")\n",
        "ax.axhline(t_phys_inj[0], color='k', lw=0.6)\n",
        "ax.set_xlabel('arclength along fault [m]')\n",
        "ax.set_ylabel('t [s]')\n",
        "ax.set_title(r'$\\{\\!\\!\\{p\\}\\!\\!\\}$ on fault vs time [MPa]'\n",
        "             f' (max = {_pmax:.3g} MPa, $\\\\Delta p_c$ = {delta_p_crit_phys:.2f} MPa)')\n",
        "fig.colorbar(im_p, ax=ax, label='[MPa]')\n",
        "\n",
        "plt.show()\n",
        "\n",
        "_first_slip_idx = np.argmax(slip_active_inj.any(axis=1)) if slip_active_inj.any() else -1\n",
        "if _first_slip_idx > 0:\n",
        "    print(f\"first slip detected at t = {t_phys_inj[_first_slip_idx]:.2f} s \"\n",
        "          f\"(dimensionless {t_inj[_first_slip_idx]:.3g})\")\n",
        "else:\n",
        "    print(\"no slip detected over the simulation horizon -- raise Q_INJ_PEAK or extend TMAX_PHYS_INJ\")\n"
    ],
}

CELL_DASHBOARD_INJ = {
    "cell_type": "code",
    "id": "inj_dashboard",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# Time-resolved CG dashboard for the injection run -- mirrors the locked\n",
        "# and sliding sections.  Use the slider to scrub through pressure,\n",
        "# displacement, elastic stress, viscous stress, total stress, strain.\n",
        "z_inj = y_inj[:, :n_base_inj]\n",
        "\n",
        "fields_inj = poro_inj.sol_to_fields_dict_with_dimensions(\n",
        "    np.asarray(t_inj),\n",
        "    z_inj.T,\n",
        "    use_taylor_correction=False,\n",
        "    constrained_l2=False,\n",
        ")\n",
        "fields_inj['y_raw'] = z_inj.T\n",
        "fields_inj['t_raw'] = np.asarray(t_inj)\n",
        "\n",
        "dashboard_inj = CGPoroelasticDashboard(poro_inj, fields_inj, levels=40)\n",
        "dashboard_inj.show()\n",
    ],
}

NEW_CELLS = [
    CELL_HEADER_INJ,
    CELL_PARAMS_INJ,
    CELL_BUILD_INJ,
    CELL_AUG_INJ,
    CELL_SOLVE_INJ,
    CELL_POST_INJ,
    CELL_DASHBOARD_INJ,
]
NEW_IDS = {c["id"] for c in NEW_CELLS}


def main():
    nb = json.loads(NB_PATH.read_text())
    cells = nb["cells"]

    # Strip any prior copies of inj_* cells, regardless of position
    cells = [c for c in cells if c.get("id") not in NEW_IDS]

    # Find insertion point: before any trailing empty cells at the very end
    insert_at = len(cells)
    while insert_at > 0:
        prev = cells[insert_at - 1]
        if prev.get("cell_type") == "code" and "".join(prev.get("source", [])).strip() == "":
            insert_at -= 1
        else:
            break

    cells = cells[:insert_at] + NEW_CELLS + cells[insert_at:]
    nb["cells"] = cells
    NB_PATH.write_text(json.dumps(nb, indent=1) + "\n")
    print(f"inserted {len(NEW_CELLS)} cells at index {insert_at}; total cells now {len(cells)}")


if __name__ == "__main__":
    main()
